Console.Write("Введите ваше имя ");
string name = Console.ReadLine();
Console.Write("Введите ваш возраст ");
byte age = byte.Parse(Console.ReadLine());
Console.Write("Введите ваш рост ");
int height = Convert.ToInt32(Console.ReadLine());
Console.Write("Укажите вашу дату рождения ");
DateOnly date = DateOnly.Parse(Console.ReadLine());
Console.Write("Давайте проверим информацию: ");
Console.WriteLine("Вас зовут {0}, Вам {1} лет, Ваш рост {2} см, Ваша дата рождения {3}", name, age, height, date);
Console.ReadKey();